### ISSUE TITLE
Building Chrome/Chromium OS for routers

### ISSUE THREAD

**Issue by fonix232** [marcosscriven/galeforce#1]
Okay this is slightly irrelevant but I couldn't find a way to contact you privately.

So if I'm reading the sources, etc. right, it should be possible in theory to build Chrome/Chromium OS for routers, making them somewhat close to the Google Wifi, right? (Chrome OS would mean Chromium + added Google bits from an official firmware for the same platform e.g. ARM, MIPS, etc.).

**Comment by marcosscriven** [comment]
Hi @fonix232 

Do you mean to compile Chromium OS from source, for the Google Wifi, so that it's as close as possible to the official ChromeOS build?

If you really wanted to do that, I'd look at the [ones here](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices), order by date descending, and [look at the overlays](https://chromium.googlesource.com/chromiumos/overlays/board-overlays.git/+/master) for those with an ARM arch. You'd have to then fish a lot of drivers and router-specific stuff out of the official firmware though.

However, this is a bottom-up approach that I would imagine would be quite a bit of work, especially if you wanted to keep it up to date with the official builds. The main reason I approached it this way (by patching the official recovery image), is I wanted minimal changes, so that all the official automatic updates and the app would work. 

That's to say - I always want the latest fixes and security patches from Google, and for its normal functions to be entirely untouched. It's just the ability to add small extras - but then be able to revert to an otherwise vanilla consumer experience.

I've spent time before fiddling with DD-WRT and it's such a hassle with security fixes, and drivers breaking.

**Comment by fonix232** [comment]
Hi @marcosscriven 

Thanks for the prompt response 😄 No, I meant compiling ChromiumOS for another router, say, a TP-Link model (with similar capabilities of course), and have it act somewhat as a Google Wifi.

Making it up-to-date is not necessarily an issue, I believe a Travis instance can be set up to compile every once in a while, and push the binary to Github Releases.

**Comment by marcosscriven** [comment]
Possibly, is about the strongest answer I can give you. What makes the Google Wifi in particular attractive to me is its mesh networking - from a hardware point of view my understanding is that's based on a Qualcomm chip. That, combined with Google's software that works out the best settings for you, is unique at the consumer level. If you wanted to modify the TPLink, you're better off looking at the recovery image for that. It would be no mean feat, and I'm not sure why you'd not just use the Google Wifi?

Regarding keeping it up-to-date - if only it were as simple as just re-compiling newer code. You'd have to constantly sort out conflicts and configuration changes; which sounds like a perfectly interesting thing to be doing for work, but not really feasible as an evenings-and-weekends project.

**Comment by fonix232** [comment]
I'd not use Google Wifi because I already have a very capable router (Asus RT-AC68U), and I'd like some Google goodies with it :) On the other hand the cheapest I could get a 3-set of Google Wifis is 400 euros. Which is a bit too much just to have wifi in my flat.

**Comment by marcosscriven** [comment]
Ah I see - well good luck. Let me know how you get on.
