### ISSUE TITLE
Recommendations for setting up OpenVPN

### ISSUE THREAD

**Issue by jofan** [marcosscriven/galeforce#11]
I'm trying to setup OpenVPN but not having any luck. I tried setting up from source but I get stuck on setting up the dependencies. I'm now thinking of trying to get Portage up and running and install it that way.

If anybody has experience getting OpenVPN to run on a system like this I'd love some help.

**Comment by drewmullen** [comment]
you make any progress on this? im just starting to look into it now

**Comment by drewmullen** [comment]
I spent some time playing around with this and it seems pretty difficult. Some notes:

1. device doesn't have a package manager (not even portage)
2. device doesn't have make or python so you cant compile from source

It does have RPM / DPKG so i tried downloading a version of openvpn.rpm with wget from rpmfind.net and the dependencies (which arent listed anywhere i can find) involved eventually installing systemd. i eventually ran into an issue where i couldnt find libraries that were compiled for arm7l architecture and stopped there.

i can see a few ways to get this going... 1. install a PM like portage and do the install with that or 2. find an older version of openvpn that clearly lists the dependencies, isn't too invasive to install, and the version hasnt been compromised

if im missing something easy here to get this installed / running, please let me know! would love to get openvpn running on this thing!

**Comment by PuffinRub** [comment]
I'd also welcome some suggestions on how to get OpenVPN installed (or a package manager of some description) using just the tools on the rooted Google WiFi box.  It's not possible to compile from sources due to the lack of Python support and there's no apt-get to easily install needed packages.   Any suggestions from the author welcomed.

**Comment by Vaayl** [comment]
I was able to make some progress myself by installing the Chromebrew package manager which I found on this site.  https://solarianprogrammer.com/2017/09/13/chrome-os-native-development/

One thing to note with Chromebrew is you need to modify the scripts to remove the --keep-directory-symlink option for tar since the version built into Busybox does not support it.  I also had some issues with the sha256sum automatic check the install.sh file did even though a manual check of the files was fine.

That allowed me to install the build essentials to get GCC 4.9 and make.  I have just started playing around trying to compile OpenVPN, but no luck as of yet.  Any suggestions from anybody would be helpful.

**Comment by TrevorBenson** [comment]
@Vaayl Have you any progress with OpenVPN? I was thinking of doing the same for OpenConnect but wanted to check if anyone has had luck.

**Comment by Vaayl** [comment]
After a bit of work and upgrading Chromebrew to install GCC 7 I was able to get OpenVPN compiled and connected with a certificate.  As this was my first time configuring OpenVPN from scratch I think I had some config problems and possibly didn't setup the NAT correctly as I was unable to actually get anywhere.  I am not putting much effort into it at the moment though as it just something to play with when I have free time.

**Comment by evliu** [comment]
Has anyone tried installing Chromebrew recently? I keep getting this:
```
chronos@localhost / $ wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
Password:
Downloading ruby...
######################################################################## 100.0%
Verifying ruby...
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
Verification failed, something may be wrong with the ruby download.```

**Comment by Roarrk** [comment]
Evliu - I've stopped using chromebrew but I found that I had to fix the sha256 references in the install script. There's a neater way to do it but for what I needed I just removed all the verifications like the dirty hack I am :-)
