### ISSUE TITLE
Error 404: ubuntu/zesty64

### ISSUE THREAD

**Issue by netalysisinfo** [marcosscriven/galeforce#34]
I am unable to find ubuntu/zesty64 box to download, is there anyone else having this problem?

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/zesty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/zesty64'
    default: URL: https://vagrantcloud.com/ubuntu/zesty64
==> default: Adding box 'ubuntu/zesty64' (v20171219.0.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/ubuntu/boxes/zesty64/versions/20171219.0.0/providers/virtualbox.box
    default: Download redirected to host: cloud-images.ubuntu.com
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

**Comment by tctree333** [comment]
I had this problem also. The issue is that zesty isn't supported anymore, so I just edited the Vagrantfile to use some other version. I ended up using the prebuilt image [here](https://github.com/marcosscriven/galeforce/releases), and that worked. Feel free to play around with different boxes and see if you can get it to work. https://app.vagrantup.com/boxes/search
